AWSTemplateFormatVersion:  "2010-09-09"
Description: "Create Ec2 instance"

Parameters: 
  InstanceTypeParameter:
    Description: Select instance type
    Type: String
    Default: t2.micro
    AllowedValues: 
        - t2.micro
        - m1.small
        - m1.large
    Description: Enter the Instance Type.  

Resources:
    Instance:
        Type: AWS::EC2::Instance
        Properties:
          InstanceType: !Ref InstanceTypeParameter
          ImageId: ami-06ddbc40823fba89a